version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
            - "./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            WHITEBOARD_DB_USER: ${WHITEBOARD_DB_USER}
            WHITEBOARD_DB_NAME: ${WHITEBOARD_DB_NAME}
            WHITEBOARD_DB_PASSWORD: ${WHITEBOARD_DB_PASSWORD}
            COTURN_DB_USER: ${COTURN_DB_USER}
            COTURN_DB_NAME: ${COTURN_DB_NAME}
            COTURN_DB_PASSWORD: ${COTURN_DB_PASSWORD}

    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
            - redis
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 83:80
        links:
            - php
            - whiteboard
            - media
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        environment:
            - VIRTUAL_HOST=siplo.dev
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./certs:/etc/nginx/certs
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db
        environment:
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    redis:
        image: redis:alpine
        ports:
            - 6380:6379
    whiteboard:
        build: draw
        container_name: whiteboard
        ports:
            - 9002:9002
        environment:
            DB_TYPE: mysql
            DB_USER: ${WHITEBOARD_DB_USER}
            DB_PASSWORD: ${WHITEBOARD_DB_PASSWORD}
            DB_HOST: db
            DB_NAME: ${WHITEBOARD_DB_NAME}
            VIRTUAL_HOST: whiteboard.siplo.dev
        tty: true
    media:
        build: signalmaster
        container_name: media
        ports:
            - "8888:8888"
        environment:
            VIRTUAL_HOST: media.siplo.dev
    coturn:
        build: docker-coturn
        container_name: coturn
        network_mode: host
        ports:
            - "3478:3478/udp" # STUN/TURN UDP
            - "3478:3478/tcp" # STUN/TURN TCP
            - "3479:3479/udp" # STUN/TURN UDP Alt port (RFC5780 support)
            - "3479:3479/tcp" # STUN/TURN TCP Alt port (RFC5780 support)
            - "5349:5349/udp" # STUN/TURN DTLS
            - "5349:5349/tcp" # STUN/TURN TLS
            - "5350:5350/udp" # STUN/TURN DTLS Alt port (RFC5780 support)
            - "5350:5350/tcp" # STUN/TURN TLS Alt port (RFC5780 support)
            - "49152:65535/udp" # UDP media ports for TURN relay
        environment:
            PORT: 3478
            ALT_PORT: 3479
            TLS_PORT: 5349
            TLS_ALT_PORT: 5350
            MIN_PORT: 49152
            MAX_PORT: 65535
            JSON_CONFIG: '{"config":["no-auth"]}'
            VIRTUAL_HOST: turn.siplo.dev