#!/usr/bin/env bash
# https://deninet.com/blog/1588/docker-scratch-part-5-custom-entrypoints-and-configuration
# set -m
# set -e
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}

WHITEBOARD_DB_NAME=${WHITEBOARD_DB_NAME:-whiteboard}
WHITEBOARD_DB_USER=${WHITEBOARD_DB_USER:-whiteboard}
WHITEBOARD_DB_PASSWORD=${WHITEBOARD_DB_PASSWORD:-1234}


COTURN_DB_USER=${COTURN_DB_USER:-coturn}
COTURN_DB_NAME=${COTURN_DB_NAME:-coturn}
COTURN_DB_PASSWORD=${COTURN_DB_PASSWORD:-1234}

# mysqld_safe &

mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${WHITEBOARD_DB_NAME}"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL ON ${WHITEBOARD_DB_NAME}.* to '${WHITEBOARD_DB_USER}'@'%' IDENTIFIED BY '${WHITEBOARD_DB_PASSWORD}'"

mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${COTURN_DB_NAME}"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL ON ${COTURN_DB_NAME}.* to '${COTURN_DB_USER}'@'%' IDENTIFIED BY '${COTURN_DB_PASSWORD}'"

mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "FLUSH PRIVILEGES"



# fg